spring:
  application:
    name: helloService

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        heart-beat-interval: 500
        heart-beat-timeout: 5000

#      username: nacos
#      password: nacos
a:
  b: hello-test

server:
  port: 9000
