spring:
  application:
    name: helloService-consumer

  cloud:
    nacos:
        discovery:
          server-addr: 127.0.0.1:8848
#          username: nacos
#          password: nacos



server:
  port: 9100

# 服务名称
#helloService:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule